<?php

/**
 * @file
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Get allowed values for theme.
 */
function donl_theme_allowed_values(FieldStorageConfig $definition, ContentEntityInterface $entity = NULL, $cacheable = TRUE) {
  /* @var \Drupal\donl_value_list\ValueListInterface $valueList */
  $valueList = \Drupal::service('donl.value_list');

  $sortedList = [];

  $list = $valueList->getHierarchicalThemeList();

  foreach ($list as $listItem) {
    $sortedList[] = $listItem['label'];
    foreach ($listItem['children'] as $child) {
      $sortedList[] = ' -- ' . $child['label'];
    }
  }

  return $sortedList;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function donl_appliance_form_node_appliance_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['actions']['submit']['#submit'][] = 'donl_appliance_custom_message_submit';
}

/**
 * Custom submit for application form.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function donl_appliance_custom_message_submit(array $form, FormStateInterface $form_state) {
  $messenger = \Drupal::messenger();

  $messenger->deleteAll();
  $messenger->addMessage(t('The application is being verified and awaiting approval.'));

  $form_state->setRedirect('donl_search.search.application');
}
