<?php

/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function donl_statistics_theme($existing, $type, $theme, $path) {
  return [
    'statistics_owners_per_chart' => [
      'variables' => [
        'data' => NULL,
      ],
    ],
    'IWDashboard' => [
      'variables' => [
        'status_table' => NULL,
        'dataset_quality' => NULL,
        'most_recent' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function donl_statistics_cron() {
  \Drupal::service('donl_statistics.collect')->collect();
}
